export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTRATION = "USER_REGISTRATION";
export const WORKSHOPS_FILTER = "WORKSHOPS_FILTER"; 
// (WORKSHOP FILTER) ^= CONCEPT TEST, CAN BE ERRASED IF DUPLICATE OR SIMILAR TO OTHER (GREETINGS MATIAS)
